### ISSUE TITLE
Setting up authentication

### ISSUE THREAD

**Issue by MCWertGaming** [MyArtverse-Project/API#6]
How do we want to setup authentication for the backend? I personally thought that we will just host the front and backend of the same URI so I can handle the authentication so that there is no need for moving the session token around, but I saw that on notion @kuroji-fusky used a bearer token to handle that in the curl example.

Should I just move to baerer tokens then? Or what are we looking forward to? The basic session stuff is done now, but it needs a bit more work to really work flawlessly. So I would be glad if we could set our desired approach in the next days.

**Comment by kuroji-fusky** [comment]
This is supposed to be internal stuff, goddamnit
